### ISSUE TITLE
False Dependency On Optional GLES 

### ISSUE THREAD

**Issue by fundamental** [IceDragon200/mruby-nanovg#1]
While this package requires some GL implementation, GLES isn't available on all platforms and it causes the build to fail on systems which have a non-ES implementation. Both this package and your glfw3 fork require mruby-gles in their rake files creating a problem.

Could you remove this gem dependency?

**Comment by IceDragon200** [comment]
@fundamental I've been meaning to remove them (the dependencies)
https://github.com/IceDragon200/mruby-nanovg/commit/445f99b270be9fca74f9eddebcfe25eafc93c1ad

The only issue right now, is that tests may fail, since mruby isolates the gems for testing and only loads their dependencies.

If this is ok, I'll close the issue, lemme know

**Comment by fundamental** [comment]
Yeah, that should be good. I didn't know about the testing situation, though I'm still getting started with mruby.
Thanks for the quick response
